# Jekyll configuration
name: UMass CICS GradReps Homepage
description: Your one stop for the latest news in CICS.

# This can be '' to hide the Github nav button
github: 'UMassGradReps/umassgradreps.github.io'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: umasscicsgradreps
comments: true

permalink: /:year/:month/:day/:title
paginate: 3

markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
gems: ['jekyll-paginate', 'jekyll-mentions']

exclude: ['README.md', 'LICENSE']

collections:
  current_gradreps:
    output: true
  former_gradreps:
    output: false
  resources:	
    output: true
    permalink: /resources/:name/